version: "3"
services:
    collabon:
        container_name: collabon
        build:
            context: ./collabon
        networks:
            - backend
        ports:
            - '3000:3000'
    frontend:
        container_name: frontend
        build:
            context: ./frontend
        networks:
            - backend
        links:
            - collabon
            - helper-service
        ports:
            - '80:80'
        environment:  
            - BACKEND_URL=http://localhost:3000/api
    redis:
        image: "redis:alpine"
        container_name: cache
        logging:
            driver: none
        networks:
            - backend
        ports:
            - 6379:6379
    helper-service:
        container_name: helper-service
        build:
            context: ./helper-service
        depends_on:
            - redis
        links:
            - redis
        networks:
            - backend
        ports:
            - 4000:4000
networks:
    backend:
        driver: "bridge"
